
title: 任务
type: kk/micro

services:
  TODO:
    title: 任务
    tasks:
      Create:
        title: 创建
        name: todo/create
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: uid
            title: 用户ID
            type: long
          - name: title
            title: 说明
            type: string
          - name: tags
            title: 标签 逗号分割
            type: string
          - name: maxUserCount
            title: 最大用户数限制
            type: long
          - name: options
            title: 其他数据
            type: object
        output:
          - name: todo
            title: TODO
            omitempty: true
            type: Todo
      Set:
        title: 修改
        name: todo/set
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: ID
            type: long
          - name: uid
            title: 用户ID
            type: object
          - name: maxUserCount
            title: 最大用户数限制
            type: object
          - name: status
            title: 状态
            type: object
          - name: title
            title: 说明
            type: string
          - name: tags
            title: 标签 逗号分割
            type: object
          - name: options
            title: 其他数据
            type: object
        output:
          - name: todo
            title: TODO
            omitempty: true
            type: Todo
      Get:
        title: 获取
        name: todo/get
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: ID
            type: long
        output:
          - name: todo
            title: TODO
            omitempty: true
            type: Todo
      Remove:
        title: 删除
        name: todo/remove
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: ID
            type: long
        output:
          - name: todo
            title: TODO
            omitempty: true
            type: Todo
      Query:
        title: 查询
        name: todo/query
        type: query
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: 任务ID
            type: long
          - name: uid
            title: 创建者ID
            type: object
          - name: fuid
            title: 创建者ID/加入用户ID
            type: object
          - name: q
            type: string
            title: 关键字
          - name: tags
            title: 标签
            type: string
          - name: status
            title: 状态 多个逗号分割
            type: string
          - name: minUserCount
            title: 最小剩余用户数
            type: long
          - name: orderBy
            type: string
            title: desc 降序默认 asc 升序 endTime 结束时间升序
        output:
          - name: todos
            title: TODO
            omitempty: true
            type: Todo[]

  User:
    title: 用户服务
    tasks:
      UserJoin:
        title: 加入
        name: user/join
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: 任务ID
            type: long
          - name: uid
            title: 用户ID
            type: long
          - name: title
            title: 说明
            type: string
          - name: status
            title: 状态
            type: int
          - name: options
            title: 其他数据
            type: object
        output:
          - name: user
            title: 用户
            omitempty: true
            type: User
      UserRemove:
        title: 删除
        name: user/remove
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: 任务ID
            type: long
          - name: uid
            title: 用户ID
            type: long
        output:
          - name: user
            title: 用户
            omitempty: true
            type: User
      UserGet:
        title: 获取
        name: user/get
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: 任务ID
            type: long
          - name: uid
            title: 用户ID
            type: long
        output:
          - name: user
            title: 用户
            omitempty: true
            type: User
      UserQuery:
        title: 查询
        name: user/query
        type: query
        input:
          - name: pid
            title: 父级ID
            type: long
          - name: id
            title: 任务ID
            type: long
          - name: uid
            title: 用户ID
            type: object
          - name: status
            title: 状态多个逗号分割
            type: string
          - name: orderBy
            type: string
            title: desc 降序默认 asc 升序
        output:
          - name: users
            title: 用户
            omitempty: true
            type: User[]
  Tag:
    title: 任务标签
    tasks:
      TagQuery:
        title: 查询标签
        name: tag/query
        input:
          - name: pid
            title: 父级ID
            type: long
      TagCounterQuery:
        title: 查询标签计数
        name: tag/counter/query
        input:
          - name: pid
            title: 父级ID
            type: long
      TagCounterGet:
        title: 获取标签计数
        name: tag/counter/get
        input:
          - name: pid
            title: 父级ID
            type: long


            
            
objects:
  Todo:
    title: TODO
    name: todo
    type: db
    fields:
      - name: pid
        title: 父级ID
        type: long
        index: asc
      - name: title
        type: string
        length: 255
        title: 说明
      - name: uid
        type: long
        title: 用户ID
        index: asc
      - name: status
        type: int
        title: 状态
        index: asc
      - name: userCount
        type: long
        title: 用户数量
      - name: maxUserCount
        type: long
        title: 最大用户数 0为不限制
      - name: options
        type: object
        title: 其他数据
      - name: ctime
        type: long
        title: 创建时间
      - name: mtime
        type: long
        title: 修改时间
  User:
    title: 用户
    name: user
    type: db
    fields:
      - name: pid
        title: 父级ID
        type: long
        index: asc
      - name: uid
        type: long
        title: 用户ID
        index: asc
      - name: todoId
        type: long
        title: 任务ID
        index: asc
      - name: title
        type: string
        length: 255
        title: 说明
      - name: status
        type: int
        title: 状态
        index: asc
      - name: options
        type: object
        title: 其他数据
      - name: ctime
        type: long
        title: 创建时间
      - name: mtime
        type: long
        title: 修改时间
        